techservicesillinois/awscli-login

src/awscli_login/__init__.py
src/awscli_login/__main__.py
src/awscli_login/config.py
src/awscli_login/util.py

Addresses #6 somewhat.  if duration is set, daemon will not run so token will not refresh. Duration is also passed in assume_role_with_saml if given.
I started using this plugin yesterday and from what I can tell, these changes don't affect how anything currently works.  Profiles without duration continue to function normally.

Add duration option; allows getting token only once.

---

src/awscli_login/__main__.py
src/awscli_login/config.py
src/tests/config/test_profile.py

In previous releases verbose could be set in the config file but it had no
effect.

Remove verbose property from config file

---

src/awscli_login/config.py
src/tests/config/test_get_credentials.py

In previous releases the password set via the config file or command
line was ignored. If the keyring was enabled it was used, if it was
not set then user was prompted for the password.
Now the password property and flag are respected. If the keyring
is enabled it is used, and the password property and flag are still
ignored. If the keyring is enabled, but not yet set then the user
is prompted even if a password is given via the password property
or flag. The keyring is preferred because it is more secure storage.

Fix broken password property and flag

---

src/awscli_login/__main__.py

In the previous release, on an unknown exception the error_handler
printed the traceback directly to stdout. This was left in by mistake
during development.
Now as before an error message is logged to error, and the traceback
is logged to debug. The traceback can be seen by a user by passing
the flag --verbose twice.

Remove old debugging code

---

src/awscli_login/config.py
src/tests/config/test_get_credentials.py

In previous releases a passcode set via the config file or command
line was ignored. Now if the factor is set to passcode and the
passcode property and flag are set, then the user is not prompted
for a code.

Fix broken passcode property and flag

---

src/awscli_login/__main__.py
src/awscli_login/config.py
src/awscli_login/util.py

In previous releases the refresh value set via the config file or command
line was ignored. This is no longer the case.

Fix broken refresh property and flag

---

src/awscli_login/__main__.py
src/awscli_login/config.py

In previous releases on initial login when the force-refresh value
was set it prevented login. If set after login it caused another
login and role selection.
This commit forbids force-refresh in the config file. When used via
the cli on initial login it is ignored and a warning issued. On use
after login it sends a SIGINT signal to the refresh process that
triggers a refresh.

Fix broken force-refresh flag

---

src/awscli_login/__main__.py

The duration was being casted to a str from an int. During testing
I found that botocore throws a ParamValidationError if duration is
of type str. Passing the duration as an int resolves the error.
Closes #38

Fix duration type error

---

src/awscli_login/config.py
src/tests/config/test_profile.py

During testing, `--disable-refresh False` failed to override the
default True value. This fix changes the logic so that properties
are overwritten as long as an argument is not None. Before it only
overwrote a property if an argument value was logically True. This
bug effects every command line argument that overrides a property.

Allow cli flags to set logically False values

---

CHANGELOG.rst

The CHANGELOG is in reStructuredText and stylized as a release history so that it can be reused as is in Sphinx documentation. For that reason it is only loosely based on the [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) markdown format.
The version links in the example from [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) link to Github diffs. The links in the CHANGELOG I authored link to the corresponding release on PyPI which seems much more useful to end users. I think developers can figure out how to generate a diff if they need one.
If the team objects to deviating from the [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) example I can easily change the format, but will lose the ability to import the CHANGELOG directly into the documentation.

Add CHANGELOG.rst

---

CHANGELOG.rst
src/awscli_login/exceptions.py
src/awscli_login/util.py
src/tests/test_util.py

In previous releases an invalid selection caused a traceback to be
printed to the user. In the current release no error message is
displayed. With this commit an error message is issued to the user
on an invalid selection. This is sufficient since the user does not
need to reauthenticate on additional login attempts.

Add invalid selection error message

---

README.rst

Adds an End-of-Life and End-of-Support date, matching that of Python 3.9 to our README.
This date will be updated as we merge updates to this product that increase it's expected lifespan.

Added anticipated end of life - based on AWSCLI V1 and Python 3.9

---

CHANGELOG.rst
setup.py
src/awscli_login/__main__.py
src/awscli_login/util.py
src/tests/test_util.py

Removing boto3 because it is completely unnecessary, and incompatible
with awscliv2 (See link below). botocore is being used instead where
boto3 was used before.
https://github.com/boto/boto3/issues/2571
Fixes #37
Fixes #44

Drop boto3 dependency

---

.github/workflows/cicd.yml
Makefile
src/tests/util.py

From time to time the cached virtual environments become corrupted
requiring a cache invalidation. This commit adds automatic cache
invalidation that does not require manual intervention by a repository
administrator.
- Adds a cache-validation action to validate paths using MD5 hashes
- Adds a workflow to run unit tests for the cache-validation action
- Adds cache validation to the primary Github workflow

Automate Github Actions' Cache Invalidation

---

.github/workflows/cicd.yml
Makefile
setup.py
src/tests/config/test_get_credentials.py
tox.ini

awscli v1 no longer supports Python 3.6 as of 5/30/2022:
https://github.com/aws/aws-cli/blob/develop/UPGRADE_PY3.md

Drop support for Python 3.6

---

src/awscli_login/plugin/__init__.py
src/awscli_login/util.py
src/tests/base.py
src/tests/test_configure.py
src/tests/util.py

* exit() should not be used in production code:
https://docs.python.org/3/library/constants.html#exit

Change exit to return or sys.exit

---

setup.py
src/awscli_login/exceptions.py
src/awscli_login/plugin/__init__.py
src/awscli_login/util.py
src/tests/test_util.py

These flags allow us to perform integration testing from the command
line without network access. Further they allow easy debugging of
network traffic.

Add --save-http-traffic and --load-http-traffic

---

mypy.ini
src/awscli_login/saml.py
src/awscli_login/util.py
src/tests/config/test_get_credentials.py
src/tests/config/util.py

* mypy versions newer than 0.982 no longer support implicit optional type hints causing the pipeline to fail. This commit updates all implicit optional type hints to be explicit per PEP 484.

Remove implicit optional type hints

---

docs/readme.rst
src/awscli_login/exceptions.py
src/awscli_login/plugin/__init__.py
src/tests/cli/test_logout.py
src/tests/test_configure.py

* Add newlines to ProfileNotFound error message for readability
* Rename test `test_save_credentials_default_profile` to
`test_login_configure_default_profile` for accuracy

Correct documentation typos

---

Makefile
tox.ini

* Drop incompatible and unsupported tox-pyenv
Closes #126

Fix build system to support tox 4.x

---

docs/readme.rst
src/awscli_login/config.py
src/awscli_login/plugin/__init__.py
src/awscli_login/plugin/__main__.py
src/awscli_login/saml.py
src/tests/util.py

* Allows skip of IdP SSL cert check when testing against a test IdP with a self-signed cert

New verify_ssl_certificate option

---

Makefile
src/tests/cli/test_logout.py

- Add unittest.skip tag to remove slowest test from unittest discovery and from coverage
- Add slowest test to dedicated tox testenv:slow
- Add make target for tox_slow

Split slowest test into separate tox environment

---

src/integration_tests/tests/clean.bash

On error shell commands for setting up the environment varibles needed to repoduce a test are now outputed when bats is run in debug mode.

Add bats outputs test environ info for debugging

---

.github/workflows/cicd.yml

Pushes to the default branch are not being released to Test PyPI as expected. This commit fixes a typo in the workflow that caused this bug.

Fix failing Test PyPI releases

---

MANIFEST.in
src/integration_tests/tests/build.bats

Build files that are not versioned must be included in MANIFEST.in.
Closes #163

Add docs/readme.rst to build

---

src/awscli_login/logger.py
src/tests/base.py
src/tests/cli/test_logout.py

Unit tests fail since awscli is throwing SyntaxWarnings. This commit turns down the logging level for messages coming from awscli.
Closes #173

Fix broken build

---

pyproject.toml

Fix awscli_login.plugin is absent from pkg config

---

.github/workflows/cicd.yml

Correctly addresses v4 upgrade recommened by dependabot PR #206.

Upgrade actions/{upload,download}-artifact to v4

---

.github/workflows/cicd.yml
Makefile
src/integration_tests/tests/common-docker-idp.bash

* Skip Docker integration tests on macOS since Docker is not currently
supported
* Move logic for skipping Docker based integration tests from the
tests to the Makefile

Add macOS to Github Actions integration tests

---

src/awscli_login/config.py

The _error_handler incorrectly set the console logger verbosity based on arguments even when skip_args was set to True.

Fix skip_args in the _error_handler function

---

.github/workflows/cicd.yml
.gitignore
Makefile
docs/readme/body.rst
docs/readme/readme.rst
pyproject.toml
src/awscli_login/__init__.py
src/awscli_login/__main__.py
src/awscli_login/configure.py
src/awscli_login/credentials.py
src/integration_tests/tests/base.bash
src/integration_tests/tests/login.bats
src/integration_tests/tests/login_configure.bats
src/tests/test_main.py

Plan is to drop the daemon, and use an external script for rotating the credentials.
Things left TODO:
+ [x] Fix failure to overwrite existing keys when setting `credential_process` in `~/.aws/credentials` during `aws configure` #195.
+ [x] Update documentation for V2 (See [here](https://github.com/wbingli/awscli-plugin-endpoint/blob/master/README.md) for an example)
+ [x] Add Python 3.11 to testing matrix
+ [x] Drop `awscli` dependency
+ [x] Test with awscli v2 (See [Upgrade docs](https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration-changes.html#cliv2-migration-profile-plugins))
+ [x] Split awscli_login into two or three submodules.
+ [x] Need a submodule that contains the plugins `login`, `logout`, and `configure`
+ [x] Add error handler to `aws_get_credentials`
+ [x] Rename …

Add V2 support

---

.github/workflows/cicd.yml
CONTRIBUTING.md
Makefile
docs/readme/header.rst
pyproject.toml
src/awscli_login/const.py
src/awscli_login/util.py
tox.ini

Add support for Python 3.13
* Add better error messages to raise_if_credential_process_not_set
* Drop support for Python 3.8
Close #218
Close #225
Close #233
Close #234

Add support for Python 3.13

---

src/awscli_login/credentials.py

* Add pyinstaller environment variables to ignore list for flag --debug-info.
Closes #242

Fix broken Windows integration tests

---

src/awscli_login/__init__.py

* Change cli flag `--http_header_factor` to `--http-header-factor`
* Change cli flag `--http_header_passcode` to `--http-header-passcode`
Closes #137

Fix CLI option underscores to hyphens
