src/awscli_login/saml.py
Taken from Cornell:
https://github.com/techservicesillinois/awscli-login/compare/master...CU-CommunityApps:master
=> Fix for https://github.com/techservicesillinois/awscli-login/issues/41

src/awscli_login/config.py, src/awscli_login/const.py, src/tests/config/test_get_credentials.py
* Tests now use new headers
* Before depreciated headers were used
* Code and tests are DRYer
=> Remove hardcoded header strings

Makefile
Forgot to update clean target in commit 87ef02.
=> Update Makefile clean target to remove .twinecheck

README.rst
+ Adds language to encourage users to upgrade to the latest `setuptools` which helps prevent issue #83.
=> Helpful message until we can automatically solve #83.

Makefile
=> Fix missing test dependencies

.github/workflows/cicd.yml, .gitmodules, Makefile, src/integration_tests/Makefile, src/integration_tests/cassettes/login.yaml, src/integration_tests/tests/base.bash, src/integration_tests/tests/clean.bash, src/integration_tests/tests/common.bash, src/integration_tests/tests/configure.bats, src/integration_tests/tests/login.bats, src/integration_tests/tests/login_configure.bats
These integration tests are for aws v1 but should work with aws v2. This PR is ready to merge after review. Unfortently, the tests are failing due to caching issues... (https://github.com/techservicesillinois/cache-validation/issues/23)
=> Add integration tests

src/awscli_login/config.py, src/awscli_login/plugin/__main__.py
=> Drop use of deprecated warn method

src/awscli_login/plugin/__init__.py, src/integration_tests/tests/docker-idp-login.bats
=> Fix --ecp-endpoint-url

.github/workflows/cicd.yml, .gitignore, Makefile
=> Parallelize Github unit and integration tests

.github/workflows/cicd.yml
=> Remove Github Actions redundancy

src/awscli_login/config.py, src/awscli_login/logger.py, src/awscli_login/plugin/__main__.py
=> Remove support for log directory

.github/workflows/cicd.yml
Adds code to correctly include the test readme.rst into the test PyPI build.
=> Fix test PyPI readme.rst build

Makefile
=> Fix make target .install

src/awscli_login/plugin/__main__.py, src/tests/config/test_profile.py
=> Fix unit test deprecation warnings

Makefile
=> Fix upload wheel & source on PyPI release

.github/workflows/cicd.yml, .gitignore, Makefile, tox.ini
* Adds wheel and sdist as targets: the target file names are calculated using setuptools_scm
* Makes build a phony target for the wheel and sdist
* Adds py312 & removes py37 from tox.ini
Closes #175
=> Update Makefile and tox.ini

.github/workflows/cicd.yml
=> Fix publish stage

.coveragerc, src/tests/test_main.py
=> Add unit tests to increase coverage

src/awscli_login/__init__.py
=> Update logout help mesg to match current behavior

src/awscli_login/util.py, src/integration_tests/tests/login_configure.bats
=> Overwrite empty aws-cli credentials on config

src/awscli_login/__init__.py, src/awscli_login/credentials.py, src/integration_tests/tests/login.bats
=> Fix C library conflicts

src/awscli_login/__init__.py, src/awscli_login/__main__.py, src/awscli_login/config.py, src/integration_tests/tests/duo.bash, src/integration_tests/tests/login.bats, src/integration_tests/tests/profiles.bats
=> Add --all flag to logout

.github/workflows/cicd.yml
* Also fix workflow warnings about key collisions
Closes #237
=> Replace deprecated set-output workflow command

CHANGELOG.rst, LICENSE, pyproject.toml
Closes #231
Closes #95
Closes #44
=> Release v1.0

.github/workflows/cicd.yml
=> Fix release on tag

src/integration_tests/tests/clean.bash
=> Fix unset AWS_PROFILE in integration tests

docs/readme/body.rst, src/awscli_login/__init__.py, src/awscli_login/__main__.py, src/awscli_login/account_names.py, src/awscli_login/config.py, src/awscli_login/credentials.py, src/awscli_login/exceptions.py, src/awscli_login/util.py, src/tests/login.py, src/tests/test_account_names.py, src/tests/test_main.py
=> Add account name alias support
